services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    image: etl_virtualherbarium:latest
    working_dir: /app
    volumes:
      - ./config-mappings:/app/config-mappings
      - ./data:/app/data
      - ./logs:/app/logs

