services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    image: etl_virtualherbarium:latest
    working_dir: /app
    volumes:
      - ./config-mappings:/app/config-mappings
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      CONFIG_PATH: config-mappings/ume.yml
      ACTION: process
    command:
      - python
      - main.py
      - --config
      - ${CONFIG_PATH:-config-mappings/ume.yml}
      - --action
      - ${ACTION:-process}
